### PR TITLE
Update deu.xaml for MM9

### PR DESCRIPTION
**Pull request by Herobrine24**

### CODE REVIEW

**Comment by Mgamerz** [comment]
Thanks for this. I will hold off on merging it for a bit since I expect a few more strings to trickle in and once merged it requires a new PR.

**Comment by Mgamerz** [comment]
Okay, should be good to go once you add the last set of strings. Hopefully won't have to add any more strings, unless knighthawk finds a 2 meter wide thermal exhaust port in the app.

**Comment by Herobrine24** [comment]
Knighthawk Edition committed on my PR branch. Is a new PR required or are the commits to the existing one enough?
(Same for https://github.com/ME3Tweaks/ME3TweaksCore/pull/21 )

**Comment by Mgamerz** [comment]
Once a PR is merged a new PR must be opened. However, an existing PR will be updated if the source branch gets new commits.

**Comment by Mgamerz** [comment]
Merging this for the beta build. Open a new PR for the new strings.

**Pull request merged**
